templates:
  - readme C: README_C.template
  - readme AVR: README_AVR.template
  - readme STM: README_STM.template
  - readme RPI: README_RPI.template
  - readme C++: README_CC.template
  - readme Vala: README_VALA.template
  - readme Perl: README_PL.template
  - readme Python: README_PY.template
  - readme Bash Shell: README_SH.template
  - readme Java Script: README_JS.template
  - cancel: null

module: README_PRO.md
